/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  oneweek: [
    {
      type: 'autogenerated',
      dirName: '21년07월',
    },
  ],
  // twodweek: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'twoweek',
  //   },
  // ],
  // threeweek: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'threeweek',
  //   },
  // ],
  // frontend: [
  //   {
  //     type: 'autogenerated',
  //     dirName: 'TIL',
  //   },
  // ],
};
